### ISSUE TITLE
Check sources: affricate place mismatch

### ISSUE THREAD

**Issue by drammock** [phoible/phoible#10]
Languages `ahk` (Akha) and `pib` (Yine) in the UW data have affricates where the stop and fricative parts don't match in place of articulation:  `tç` and `tçʰ`

**Comment by drammock** [comment]
I checked the Yine article, and it just says "palatal affricate" which suggests changing from `tç` to `cç`. I don't have the Akha source.

**Comment by bambooforest** [comment]
Emailing you the article. What about these squibs anyway? Should we host them somewhere?

**Comment by drammock** [comment]
@drammock steals the ball from @bambooforest, passes to @drammock, its @drammock, @drammock all the way...  GOOOOOAL!!
