### ISSUE TITLE
Fix GM README

### ISSUE THREAD

**Issue by drammock** [phoible/phoible#32]
There are some remarks in there that don't seem to be true (e.g., about having merged the Africa and SE Asia data into one source file).  Fix after #28 is merged.

**Comment by drammock** [comment]
@bambooforest is this still on your radar?  You merged #28 long ago.

**Comment by bambooforest** [comment]
Do you want me to merge the GM files into one? I'm not sure what you're asking here.

We agreed we would skip the demographics (population) and genealogy comes for "free" when we merge in Glottolog codes.

Should we just close #32 and #28 ?

**Comment by drammock** [comment]
I don't think it's necessary to merge the source files into one.  I just
want one of two things:

1. delete the GM readme (and the UPSID folder readme while you're at it;
none of the other data sub-folders have one)
2. change the GM (and UPSID) readme to be accurate/current, e.g., not
include a to-do list
