### ISSUE TITLE
Duplicate languages `izi` and `xsm` in AA raw data

### ISSUE THREAD

**Issue by drammock** [phoible/phoible#64]
AA raw data has three different lects listed under ISO code `izi`:

- Lines 2480-2517 are `LanguageName` "ẹzaa"
- Lines 3716-3755 are `LanguageName` "ikwo"
- Lines 3757-3826 are `LanguageName` "izi"

This breaks the trump selection procedure, which currenly can only handle:

- same ISO code (`LanguageCode`) but different `Source`
- same ISO code and same `Source` but different `SpecificDialect`

Any idea what's going on here @bambooforest?  Can you (or one of your colleagues) examine the raw AA data and figure out what to do here? Possible solutions I can see are:

1. keep all three, but add `SpecificDialect` information to each (in AA data, there is no `SpecificDialect` column, so this would take the form of parenthetical info in the `LanguageName` column)
2. remove two of them, if the three are genuine duplicates (no differences in inventory), and incorporate the alternate names into the `LanguageName` field of the entry that is kept.

**Comment by drammock** [comment]
Similar problem with `LanguageCode` `xsm`:

- Lines 4182-4222 have `LanguageName` "kasem"
- Lines 4224-4268 have `LanguageName` "kasɩm"

**Comment by bambooforest** [comment]
The first problem is handled by "recent" changes to ISO 639-3, which retires [izi] and splits it into 4 separate codes:

http://www-01.sil.org/iso639-3/documentation.asp?id=izi

I've updated the AA data file. The second issue is that Kasem and Kasim are slightly reportedly mutually intelligible varieties of the same language, but one is spoken in Burkina and the other in Ghana. Ethnologue lists the Burkina variety as canonical:

http://www.ethnologue.com/language/xsm

The inventories are slightly different too. Do we want to implement implicit trump order as: the first occurrence of an ISO code *within* a particular inventories file?

**Comment by drammock** [comment]
arbitrarily choosing the first one will certainly be easier to implement than trying to add an extra trump indicator somehow. Probably fine for AA since it's a static resource and we can fix the order the way we want it. Less good for handling resources like SAPHON where we don't have control over the format of the raw data file, so we can't guarantee that the "canonical" form (according to Ethnologue or whoever) comes first in the list.

**Comment by bambooforest** [comment]
I think we can close this issue, or? Trump ordering will be handled internally by first come-first serve in alphabetic order. Other users can define trump as they fit. We will also pull in Glottolog codes (todo).
