### ISSUE TITLE
Duplicate languages `lmn` and `iru` in Ramaswami raw data

### ISSUE THREAD

**Issue by drammock** [phoible/phoible#65]
`lmn` is named as Lamani on line 60 and Banjara on line 13.

`iru` is named as Irula on line 33 and Kasaba on line 40. 

Need to determine if this is just an error of the ISO code (in which case need to correct), or if these are actually lects that are classified with the same ISO code (in which case need to figure out how to apply trump to them; easiest is probably adding parenthetical info to the `LanguageName` field).

Blocks resolution of #53.

**Comment by bambooforest** [comment]
At least the latter seems to be correct. Another option for trump ordering
might be to pull in the Glottolog codes (and canonical names) to deal with
finer-grained divisions between languages / lects, e.g. we would have Irula:

http://glottolog.org/resource/languoid/id/irul1243

and Irula Kasaba:

http://glottolog.org/resource/languoid/id/nort2701

the latter of which doesn't have an ISO code, per se. Without an ISO code,
we would have a issue trump ordering -- it would fall out. Irula has many
dialects:

http://www.ethnologue.com/language/iru

Kasaba being an alternative name for Northern Kasaba.

I'm not sure I like this solution more than the "simply take the first ISO
code in the source" solution (that's what I implemented in my thesis).
