### ISSUE TITLE
feature vectors for some phonemes not getting properly merged

### ISSUE THREAD

**Issue by drammock** [phoible/phoible#72]
out of 2211 phonemes, 221 are not merging properly, although at least some of them are definitely present in feature table.

**Comment by drammock** [comment]
221 reduced down to 28 by moving `glyphID` assignment to occur after `markMarginal`.

5 of these are possibly glyph errors in `nmn` from the `GM` datasource: `ˀnʘ`, `ˀnǁ`, `ˀnǂ`, `ˀnǀ`, `ˀnǃ` probably should all be `ŋ` instead of `n`.  A couple are bare click symbols with missing dorsal place glyphs, and most of the rest are breathy pre-aspiration phonemes.

**Comment by drammock** [comment]
This is bringing to light a number of IPA issues that I thought we had already resolved.  For example, I thought we agreed to eliminate all cases of `dʰ` in favor of `dʱ` (and similarly for all other cases of (pre-)aspiration on base segments that are voiced). Consequently I tried to just replace `dʰ` with `dʱ` in the features table, but in fact that causes lots of cases of `dʰ` (which I thought had been eliminated in the source data) to show up in the "not getting assigned a feature vector" list.  Before I start changing every single case of `ʰ` on voiced segments to `ʱ` in the source data, I wanted to check in with you @bambooforest in case I'm forgetting some past decision about keeping phonemes like `dʰ` despite their phonetically questionable status.

**Comment by bambooforest** [comment]
It looks like this was simply (and on my part) not resolved:

https://code.google.com/p/phoible/issues/detail?id=84

So perhaps the best way to deal with these and the other issues for
future's sake is to keep track of them and resolve them in these git issues
by clearly stating what and why.

So any voiced segment that is aspirated, regardless pre or post, should use
the <ʱ> U+02B1 and voiceless should be regular IPA aspirated symbol <ʰ>
U+02B0. Correct?

We have some problematic cases:

http://phoible.org/parameters/7DA7B5896CFFC7827CBFB7C325E61FAB#6/-21.289/27.401

http://phoible.org/parameters/7D6B77168A83A83505CC8AF54D22B9DC#6/-21.289/27.401

I will go through the other google code issues ASAP.

**Comment by drammock** [comment]
The aspiration issue is now #73.
