### ISSUE TITLE
aspiration in source data

### ISSUE THREAD

**Issue by drammock** [phoible/phoible#73]
There should never be a standard aspiration diacritic `ʰ` on a base glyph that is voiced. All such instances of `ʰ` in the data sources should be converted to `ʱ`. The features table will need to be updated as well, to make sure that the revised phonemes are still getting assigned a feature vector.

**Comment by bambooforest** [comment]
Are you assigning me this issue? If so, please assign and I'll take care of
both the segments in the original resources and the features in the feature
look up table.

**Comment by drammock** [comment]
done.  FYI, you can also self-assign from the right-hand column of the issue page.

**Comment by bambooforest** [comment]
but i thought maybe you wanted to take this on ;)

**Comment by bambooforest** [comment]
@drammock please advise regarding:

cɕʰ	ok		shouldn't this be t̠ɕʰ ?

for this I get three rows all from UPSID:

nbf	upsid	cɕʰ
gio	upsid	cɕʰ
cnh	upsid	cɕʰ

where we have the rows:

416	cɕʰ	cɕʰ		cC,h	voiceless aspirated palatal sibilant affricate	corrected from cʃ̠ʰ	
417	cɕ	cç		cC,	voiceless palatal sibilant affricate	corrected from cʃ̠	

in the correspondences file:


https://github.com/phoible/phoible/blob/master/data/UPSID/UPSID_IPA_correspondences.tsv#L417-L418

**Comment by drammock** [comment]
If it's "palatal", it should be cç
if it's "alveolopalatal", it should be t̠ɕ

**Comment by drammock** [comment]
linking this issue to #84

**Comment by bambooforest** [comment]
I've tracked these down in the UPSID segment / feature set:

cɕʰ
cɕ
cɕʼ
ɲcɕ

which are all:

pal = TRUE
alv = FALSE
palalv = FALSE

So I assume this OK.

**Comment by drammock** [comment]
not OK.  If these are palatal, should be c-cedilla, not c-curl.

**Comment by bambooforest** [comment]
Ok. Please advise on how to move forward. I've extracted all features from
both PHOIBLE and UPSID for the affected segments -- emailing it to you.

**Comment by drammock** [comment]
ahhh.  Palatal **sibilant** fricatives/affricates.  For UPSID, we decided long ago that "palatal non-sibilant" was c-cedilla, but "palatal sibilant" was c-curl.  So the preceding stop should become retracted t.  Sorry that I missed the word "sibilant" earlier in the issue thread.

**Comment by bambooforest** [comment]
Before I update, I did a quick and dirty query

select LanguageCode, Source, Phoneme from phoible-phoneme-level-no-trump.tsv where Phoneme like '%ɕ%'

and get this (minus the lots of rows that return simply <ɕ>:

phl	ph	tɕ
pol	ph	tɕ
aka	gm	tɕ
mij	gm	tɕ
cav	ph	tɕ
jya	ph	tɕ
pbr	gm	tɕ
tsj	ph	tɕ
kig	ph	tɕ
cmn	ph	tɕ
hrv	ph	tɕ
afu	gm	tɕ
kxm	ph	tɕ
buu	gm	tɕ
bdh	gm	tɕ
kmw	aa	tɕ
aja	gm	tɕ
bod	ph	tɕ
afo	gm	tɕ
lno	gm	tɕ
knc	aa	tɕ
krs	aa	tɕ
iri	gm	tɕ
pww	ph	tɕ
aka	gm	tɕᶣ
afu	gm	tɕᶣ
cko	gm	ɕᶣ
aka	gm	ɕᶣ
bod	ph	tɕʰ
kxm	ph	tɕʰ
cmn	ph	tɕʰ
jya	ph	tɕʰ
tsj	ph	tɕʰ
pww	ph	tɕʰ
knn	upsid	cɕ
cnh	upsid	cɕ
tel	upsid	cɕ
teh	upsid	cɕ
nbf	upsid	cɕ
gio	upsid	cɕ
brv	upsid	cɕ
nbf	upsid	cɕʰ
gio	upsid	cɕʰ
cnh	upsid	cɕʰ
gio	upsid	ɲcɕ
iri	gm	tɕʷ
kjq	upsid	ɕʼ
snk	aa	ɕː
teh	upsid	cɕʼ

UPSID could be updated as suggested:

cɕʰ
cɕ
cɕʼ
ɲcɕ

>>

t̠ɕʰ
t̠ɕ
t̠ɕʼ
ɲt̠ɕ

But anything else that <tɕ> all be retracted and the rows updated in the features file?

**Comment by bambooforest** [comment]
New issue created for this last comment about t and curl. See issue #89

**Comment by drammock** [comment]
Closing because #90 is merged.
