### ISSUE TITLE
aggregation script aggregating header row from somewhere

### ISSUE THREAD

**Issue by bambooforest** [phoible/phoible#77]
line 22611:

ISO	Name	Dialect	Phonemes	Allophones Allophones Allophones Allophones Allophones	gm	0050+0068+006F+006E+0065+006D+0065+0073	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA

**Comment by drammock** [comment]
I think this is already fixed in #70 but I'll double-check.

**Comment by drammock** [comment]
This appears to have been fixed in #70 already; when I'm working in that branch, searching for `0050+0068+006F+006E+0065+006D+0065+0073` in the `GlyphID` column gives me zero rows.
