### ISSUE TITLE
aggregating script dropping data?

### ISSUE THREAD

**Issue by bambooforest** [phoible/phoible#78]
some weird things come out of the aggregation script that i'm discovering via the R code on multivariate variables i emailed you. for example:

filter(multivariate, coronal==FALSE)

returns:

fan
ksf
mky
sgw
thm
xbr

filter(final.data, LanguageCode=="ksf") --> 7 phonemes
filter(final.data, LanguageCode=="fan") --> 1 phoneme
filter(final.data, LanguageCode=="mky") --> 1 phoneme
filter(final.data, LanguageCode=="sgw") --> 3 phonemes
filter(final.data, LanguageCode=="thm") --> 1 phoneme
filter(final.data, LanguageCode=="xbr") --> 1 phoneme

table(final.data$LanguageCode)

shows the phoneme counts are off...

**Comment by drammock** [comment]
PH source data for fan has errors in the "specific dialect" column that are
probably at fault here.  See lines 1070-1072 of the data file.

GM source data for xbr has an errant entry in the "specific dialect" column
on line 465 of the GM_SEA file. It happens to come on the very last phoneme
of the inventory, which is why it ylelds only 1 phoneme.

thm occurs twice in the PH data. I can't discern an immediate cause; will
look into it.

**Comment by drammock** [comment]
Any idea about the provenance of those spurious "dialects" on lines 1070-1072 in the Fan inventory?  

`harhar`, `ŋɡb`, `nym`

I looked through the introduction of [the source document](http://pubman.mpdl.mpg.de/pubman/item/escidoc:403463:4/component/escidoc:403462/fan_eko1974_o.pdf) and there's no obvious mention of a dialect name. OK to just delete those cells?

**Comment by drammock** [comment]
`xbr` problem addressed in #70, commit 116b87caaeb494222cbc11dce652780f7ab4346e

**Comment by bambooforest** [comment]
Yes, OK to delete those cells. Looks like some copy and paste error.

Specific Dialect Phonemes Questions
harhar ŋɡ
ŋɡb kp
nym ŋmɡb updated from ŋɡb
w

from when I was correcting Dr. Green's transcriptions.

**Comment by bambooforest** [comment]
A quick table(final.data$SpecificDialect) shows some things I could look at in more detail and correct / normalize:

Dialect 
Harar 
harhar 
macrolanguage 
nj 
northern 
Northern 
nym 
ŋɡb 
One possibility 
Ordinary'

**Comment by drammock** [comment]
I removed "One possibility".  "harhar", "nym", and "ŋɡb" came from `fan`, which is now addressed in #70. "nj" came from `xbr` which is also fixed in #70. "macrolanguage" seems like potentially good information to keep. "Ordinary" could conceivably be a dialect name, as could "Northern" or "Harar".  We should probably check the primary sources for those three.  Thanks for volunteering!

**Comment by bambooforest** [comment]
Will do!

**Comment by bambooforest** [comment]
Ordinary updated (Ordinary Kreol is the dialect) on my local fork on a branch. Harar is OK. Northern is OK. One thing we should consider is pulling in canonical language names from the Glottolog along with the Glottlog codes.

**Comment by bambooforest** [comment]
after the latest PR #70 

thm phonemes (PH) are still being dropped in aggregation

but the other problems seem to be fixed, i.e.:

filter(final.data, LanguageCode=="ksf")
filter(final.data, LanguageCode=="fan")
filter(final.data, LanguageCode=="mky")
filter(final.data, LanguageCode=="sgw")
filter(final.data, LanguageCode=="thm")
filter(final.data, LanguageCode=="xbr")

**Comment by drammock** [comment]
I think the dropping of [thm] is because if the multiple dialects of [thm]
listed in the PH raw data. I think the problem will go away when we have
proper unique doculect identifiers, but I'm working on a temporary fix in
the aggregation code in the meantime.

**Comment by bambooforest** [comment]
So multiple inventories with the same language code (and name) but
different dialect name? Perhaps all three together are a unique identifier
(at least within a given raw data input source?). I can add the InventoryID
to Glottolog IDs mapping file to the repo, if that's helpful? At least
until we figure out how to pull that stuff directly from the Glottolog repo.

**Comment by bambooforest** [comment]
note to self: ISO still showing up in the aggregated results:

filter(final.data, LanguageCode == "ISO")

**Comment by drammock** [comment]
I am simply not seeing that. When I run `"ISO" %in% final.data$LanguageCode` it says `FALSE`.

**Comment by drammock** [comment]
when was the last time you ran the full aggregation script to re-generate the .Rdata file?  Maybe you're working from an .RData file that was generated with an outdated version of the agg script.

**Comment by bambooforest** [comment]
My bad. You're right.

**Comment by drammock** [comment]
fixed in #101.
