### ISSUE TITLE
Glottal tap?

### ISSUE THREAD

**Issue by bambooforest** [phoible/phoible#83]
https://github.com/phoible/phoible/blob/master/data/PH/phoible_inventories.tsv#L743

Getting source material to double check.

**Comment by drammock** [comment]
The source material does not give any further information other than placing the symbol `x` in the table at the row and column indicating "glottal tap". There are also a couple sample words, also using `x`.  Recommend tracking down the reference cited in that document as the source of the phonological information:

> Gordon, Kent H. 1976. _Phonology of Dhangar Kurux._ Kathmandu: SIL and CNAS T.U.

**Comment by bambooforest** [comment]
I've looked all over for this, even contacted HH, but it hasn't been found.
Could you look?

**Comment by drammock** [comment]
Heh. I'll try, but I'm not even allowed inside the library here (and I
seriously doubt they would have it anyway). So if it's not online I can't
get it until at least July.

**Comment by bambooforest** [comment]
OK. I'll keep trying.
