### ISSUE TITLE
combining features

### ISSUE THREAD

**Issue by bambooforest** [phoible/phoible#87]
Right now we have an approach requires that complex segments (e.g. kp) be assigned individually, otherwise feature sets are built segment by segment. So for example:

segment	sonorant	nasal	periodicGlottalSource
cɕʼ	-	-	-
ɲcɕ	+,-,-	+,-,-	+,-,-
cɕ	-	-	-
cɕʰ	-	-	-

We may want to revisit this and propose something like collapsing sets where the feature value repeats itself, e.g. +,-,- >> +,-

**Comment by drammock** [comment]
closing per discussion on 2015.04.28.  Combining features in this way collapses distinctions between `+,+,-` and `+,-,-`
