### ISSUE TITLE
Phonemes / allophones aggregated

### ISSUE THREAD

**Issue by bambooforest** [phoible/phoible#95]
Checkout out the allophones for [nym] in final.data -- all the allophones (and I guess phonemes) are aggregated into the same inventory:

   Source LanguageCode Phoneme                                      Allophones
1      gm          nyf      kp       kp kpʰ kp kpʰ kp kpʰ kp kpʰ kp kpʰ kp kpʰ
2      gm          nyf      ɡb ɡb ŋmɡb ɡb ŋmɡb ɡb ŋmɡb ɡb ŋmɡb ɡb ŋmɡb ɡb ŋmɡb
3      gm          nyf       p                   p pʰ p pʰ p pʰ p pʰ p pʰ p pʰ
4      gm          nyf       b                   b mb b mb b mb b mb b mb b mb
5      gm          nyf       t                   t tʰ t tʰ t tʰ t tʰ t tʰ t tʰ
6      gm          nyf       d                   d nd d nd d nd d nd d nd d nd
7      gm          nyf       k                   k kʰ k kʰ k kʰ k kʰ k kʰ k kʰ
8      gm          nyf       ɡ                   ɡ ŋɡ ɡ ŋɡ ɡ ŋɡ ɡ ŋɡ ɡ ŋɡ ɡ ŋɡ

**Comment by drammock** [comment]
fixed in #101.  FYI, this was probably happening because there are 5 (five!) separate entries for `nyf` in the GM data.  With the newly-implemented Inventory IDs, they are properly segregated.

**Comment by bambooforest** [comment]
sg. merged the recent PR. we also have 5 inventories for aka but they are
spread out over different sources. should i work out a method for
incorporating glottolog ids?
